workspace:
  base: /go
  path: src/github.com/diego-fu-hs/drone

pipeline:
  backend:
    image: golang
    commands:
      - go get
      - go build
      - go test

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://dev-k8s-controllers.hootsuitemedia.com:6443
    deployment: diego-drone-deployment
    repo: diego-fu-hs/drone
    container: diego-drone-container
    tag:
      - latest
